# Docker Compose configuration for the Movie Explorer application
# This file reads configuration from a .env file in the same directory.
version: '3.8'

services:
  # Frontend Service (React/Vue/Angular served by Nginx)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: movie-explorer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - movie-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Backend Service (Node.js API)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: movie-explorer-backend
    ports:
      # The port is now dynamically set from the .env file
      - "${PORT}:${PORT}"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - movie-network
    restart: unless-stopped
    # All environment variables are loaded from the .env file
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Database Service
  mongodb:
    image: mongo:6.0
    container_name: movie-explorer-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - movie-network
    restart: unless-stopped
    # Database credentials are loaded from the .env file
    environment:
      - MONGO_INITDB_DATABASE=movie-explorer
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express (Optional Web UI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: movie-explorer-mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - movie-network
    restart: unless-stopped
    # Mongo Express configuration is loaded from the .env file
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}

# Define the network for services to communicate
networks:
  movie-network:
    driver: bridge

# Define the volume for persistent MongoDB data
volumes:
  mongodb_data:
